# Generated by Django 3.0.3 on 2020-07-17 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DesignerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='unique_name',
            field=models.CharField(default='kekwtest', max_length=256),
            preserve_default=False,
        ),
    ]
