# Generated by Django 3.0.3 on 2020-07-17 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DesignerApp', '0002_task_unique_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assistant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='DesignerApp.Assistant'),
        ),
    ]
